config/routes.rb
Bang::Application.routes.draw do

  match "/users/check_login" => "users#check_login"
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }
  root :to => "users#index"
  resources :photos, :only => ["index", "create"]
  resources :users, :only => ["show", "index"] do
    resources :photos do
      match "/users/:login" => 'users#show', :as => :login
      match "make_profile", :to => 'photos#make_profile'
      match "edit_caption", :to => 'photos#edit_caption'
      match "update_caption", :to => 'photos#update_caption'
      post :sort, on = :collection
    end
    resources :ratings  
    resources :questions, :only => ["edit", "update"]
    match "hide", :to => 'hides#create'
    match "unhide", :to => 'hides#destroy'
    match "sort", :to => 'photos#sort'
    match "rate", :to => 'ratings#browse_rate'
    match "answer_questions", :to => 'users#answer_questions'
    match "questions", :to => 'users#questions'
    match "about", :to => 'users#about'
  end
  match '/search', :to =>'users#search'
  match '/random', :to => 'users#random'
  match '/history', :to => 'users#history'
  match '/admin', :to => 'users#admin'
  match '/about', :to => 'users#learn_more'
  match '/contact', :to => 'users#contact'
  match '/send_contact', :to => 'users#send_contact'
  resources :messages do
    resources :responses
  end
  resources :questions, :only => [ :edit, :update ]
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def edit
    @user = User.find params[:user_id]
    @question = Question.find params[:id]
    respond_to do |format|
      format.js
    end
  end

  def update
    @user = User.find params[:user_id]
    @question = Question.find params[:id]
    if params[:answer]
      if params[:answer].blank?
        params[:answer] = nil
      end
      @question.update_attributes(:answer => params[:answer])
    end
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.haml
- if question.answer.nil?
	You haven't answered this question yet.  Click on the icon to the right of the question above to answer.
- else
	= simple_format(question.answer)

app/views/questions/_form.html.haml
- form_tag user_question_path(current_user, question), :method => :put, :remote => true do
	
	= text_area_tag :answer, @question.answer
	%br/
	= submit_tag "update answer", :class => "black-button"
	= link_to "cancel", user_question_path(current_user, question), :method => :put, :remote => true, :class => "cancel"

app/views/questions/edit.js.erb
$("div#<%= @question.id %>_answer").html("<%= escape_javascript(render :partial => 'form', :locals => { :question => @question }) %>");

app/views/questions/update.js.erb
$("div#<%= @question.id %>_answer").html("<%= escape_javascript(render :partial => 'answer', :locals => { :question => @question }) %>");