config/routes.rb
Bang::Application.routes.draw do

  match "/users/check_login" => "users#check_login"
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }
  root :to => "users#index"
  resources :photos, :only => ["index", "create"]
  resources :users, :only => ["show", "index"] do
    resources :photos do
      match "/users/:login" => 'users#show', :as => :login
      match "make_profile", :to => 'photos#make_profile'
      match "edit_caption", :to => 'photos#edit_caption'
      match "update_caption", :to => 'photos#update_caption'
      post :sort, on = :collection
    end
    resources :ratings  
    resources :questions, :only => ["edit", "update"]
    match "hide", :to => 'hides#create'
    match "unhide", :to => 'hides#destroy'
    match "sort", :to => 'photos#sort'
    match "rate", :to => 'ratings#browse_rate'
    match "answer_questions", :to => 'users#answer_questions'
    match "questions", :to => 'users#questions'
    match "about", :to => 'users#about'
  end
  match '/search', :to =>'users#search'
  match '/random', :to => 'users#random'
  match '/history', :to => 'users#history'
  match '/admin', :to => 'users#admin'
  match '/about', :to => 'users#learn_more'
  match '/contact', :to => 'users#contact'
  match '/send_contact', :to => 'users#send_contact'
  resources :messages do
    resources :responses
  end
  resources :questions, :only => [ :edit, :update ]
  
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout "splash"
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "splash"
  
  def edit
    render :layout => "application"
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "splash"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :check_login, :contact, :send_contact, :learn_more ]
  after_filter :add_visit, :only => [:show, :random]

  def index
    if user_signed_in?
      @similar = (current_user.matches.joins(:photos).near([current_user.latitude, current_user.longitude], 1000).sort_by(&:ratio) - current_user.hidden_users - User.where("id = ?", current_user.id)).uniq
      @similar = @similar[1..10]
      if @similar.count < 10
        @left = 10 - @similar.count
        @similar = (@similar + (current_user.matches.joins(:photos).near(current_user, 5000, :order => "distance").limit(@left) - current_user.hidden_users - User.where("id = ?", current_user.id))).uniq
      end
      @random = (current_user.browse.joins(:photos) - current_user.hidden_users - User.where("id = ?", current_user.id)).uniq
      if @random.count < 10
        @left = 10 - @random.count
        @random = (@random + (current_user.matches.joins(:photos).near(current_user, 5000, :order => "distance").limit(@left) - current_user.hidden_users - User.where("id = ?", current_user.id))).uniq
      end
      @random = @random.shuffle
      @random = @random[1..10]
    else
      render :layout => "splash"
    end
  end

  def show
    @user = User.find_by_login(params[:id])
    @photo = Photo.new
  end
  
  def search
    if current_user.looking_for_colloquial == "guys"
      @options_for_sex = [["Men", "Male"], ["Women", "Female"], ["Both", "both"]]
    elsif current_user.looking_for_colloquial == "girls"
      @options_for_sex = [["Women", "Female"], ["Men", "Male"], ["Both", "both"]]
    elsif current_user.looking_for_colloquial == "guys & girls"
      @options_for_sex = [["Women", "Female"], ["Men", "Male"], ["Both", "both"]]
    else
      @options_for_sex = [["Women", "Female"], ["Men", "Male"], ["Both", "both"]]
    end
    @options_for_distance = [["10 miles", 10], ["25 miles", 25], ["100 miles", 100], ["anywhere", 10000]]
    @options_for_order_by = [["Similarity","similarity"], ["Hotness", "hotness"], ["Newest","newest"], ["Distance","distance"]]
    @results = (current_user.matches.joins(:photos).near(current_user, 1000, :order => "distance") - current_user.hidden_users).uniq
    @results = Kaminari.paginate_array(@results).page(params[:page]).per(10)
    if params[:commit]
      if params[:min_age] && !params[:min_age].blank?
        @min_age = params[:min_age].to_i.years.ago
      else
        @min_age = 18.years.ago
      end
      if params[:max_age] && !params[:max_age].blank?
        @max_age = params[:max_age].to_i.years.ago
      else
        @max_age = 70.years.ago
      end
      if params[:order_by] == "hotness"
        if params[:sex] == "both"
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ?", @max_age, @min_age).near([current_user.latitude, current_user.longitude], params[:distance]).sort_by(&:score).reverse - current_user.hidden_users - User.where("id = ?", current_user.id)
        else
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ? AND sex = ?", @max_age, @min_age, params[:sex]).near([current_user.latitude, current_user.longitude], params[:distance]).sort_by(&:score).reverse - current_user.hidden_users - User.where("id = ?", current_user.id)
        end
        if params[:mates] == "on"
          @results = @results - current_user.mates
        end
        @results = @results.uniq
        @results = Kaminari.paginate_array(@results).page(params[:page]).per(10)
      elsif params[:order_by] == "similarity"
        if params[:sex] == "both"
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ?", @max_age, @min_age).near([current_user.latitude, current_user.longitude], params[:distance]).sort_by(&:ratio) - current_user.hidden_users - User.where("id = ?", current_user.id)
        else
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ? AND sex = ?", @max_age, @min_age, params[:sex]).near([current_user.latitude, current_user.longitude], params[:distance]).sort_by(&:ratio) - current_user.hidden_users - User.where("id = ?", current_user.id)
        end
        if params[:mates] == "on"
          @results = @results - current_user.mates
        end
        @results = @results.uniq
        @results = Kaminari.paginate_array(@results).page(params[:page]).per(10)
      elsif params[:order_by] == "newest"
        if params[:sex] == "both"
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ?", @max_age, @min_age).near([current_user.latitude, current_user.longitude], params[:distance]).order("created_at DESC") - current_user.hidden_users - User.where("id = ?", current_user.id)
        else
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ? AND sex = ?", @max_age, @min_age, params[:sex]).near([current_user.latitude, current_user.longitude], params[:distance]).order("created_at DESC") - current_user.hidden_users - User.where("id = ?", current_user.id)
        end
        if params[:mates] == "on"
          @results = @results - current_user.mates
        end
        @results = @results.uniq
        @results = Kaminari.paginate_array(@results).page(params[:page]).per(10)
      elsif params[:order_by] == "distance"
        if params[:sex] == "both"
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ?", @max_age, @min_age).near([current_user.latitude, current_user.longitude], params[:distance]).sort_by(&:distance_sort) - current_user.hidden_users - User.where("id = ?", current_user.id)
        else
          @results = User.joins(:photos).where("birthday >= ? AND birthday <= ? AND sex = ?", @max_age, @min_age, params[:sex]).near([current_user.latitude, current_user.longitude], params[:distance]).sort_by(&:distance_sort) - current_user.hidden_users - User.where("id = ?", current_user.id)
        end
        if params[:mates] == "on"
          @results = @results - current_user.mates
        end
        @results = @results.uniq
        @results = Kaminari.paginate_array(@results).page(params[:page]).per(10)
      end
    end
  end
  
  def random
    @user = (current_user.matches.joins(:photos).near(current_user, 10000, :order => "distance") - current_user.mates - current_user.hidden_users)
    @user = @user[0..10].sample
  end
  
  def about
    @user = User.find_by_login(params[:user_id])
    @photo = Photo.new
    render :show
  end
  
  def answer_questions
    @user = User.find_by_login(params[:user_id])
    unless @user == current_user
      redirect_to root_path
    end
  end
  
  def questions
    current_user.update_attributes(params[:user])
    redirect_to user_about_path(current_user.login)
  end
  
  def history 
    if params[:mates] == "matches"
      @rated = current_user.mates.where("status = ?", "bang")
      @history = Array.new
      @rated.each do |user|
        if user.mates.include?(current_user)
          unless Rating.where("user_id = ? AND mate_id = ?", user.id, current_user.id).first.status == "nope"
            @history << user
          end
        end
      end
      @count = @history.count
      @history = Kaminari.paginate_array(@history).page(params[:page]).per(10)
    elsif params[:mates] == "bang"
      @history = current_user.mates.where("status = ?", "bang")
      @count = @history.count
      @history = Kaminari.paginate_array(@history).page(params[:page]).per(10)
    elsif params[:mates] == "date"
      @history = current_user.mates.where("status = ?", "date")
      @count = @history.count
      @history = Kaminari.paginate_array(@history).page(params[:page]).per(10)
    elsif params[:mates] == "nope"
      @history = current_user.mates.where("status = ?", "nope")
      @count = @history.count
      @history = Kaminari.paginate_array(@history).page(params[:page]).per(10)
    else
      @history = current_user.mates
      @count = @history.count
      @history = Kaminari.paginate_array(@history).page(params[:page]).per(10)
    end
  end
  
  def check_login
    @user = User.where("LOWER(login) = ?", params[:user][:login].downcase)
    if @user == []
      @user = nil
    end
    respond_to do |format|
      format.json { render :json => !@user }
    end
  end
  
  def learn_more 
    render :layout => "splash"
  end
  
  def contact 
    render :layout => "splash"
  end
  
  def send_contact
    UserMailer.contact_form(params[:name], params[:email], params[:message]).deliver
    redirect_to root_path, :notice => "Your Message was sent!"
  end
  
  def admin
    unless current_user == User.find_by_login("goddamnyouryan")
      redirect_to root_path
    end
  end
  
  private
  
  def add_visit
    unless current_user == @user || @user.nil?
      @user.visits.create(:visitor_id => current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_hide.html.erb
<% if current_user.hidden_users.include?(user) %>
	<% @hide = Hide.find_by_user_id_and_hidden_id(current_user.id, user.id) %>
	<%= link_to "Un-hide", user_unhide_path(user), :method => :delete, :remote => true %>
<% else %>
	<%= link_to "Hide", user_hide_path(user), :method => :post, :remote => true %>
<% end %>

app/views/users/_nav.html.haml
%nav#user
	%ul
		- unless params[:action] == "about"
			%li= link_to "photos", user_path(@user.login), :class => "current", :id => "left-link"
			%li= link_to "about", user_about_path(@user.login), :id => "right-link"
		- else
			%li= link_to "photos", user_path(@user.login), :id => "left-link"
			%li= link_to "about", user_about_path(@user.login), :class => "current", :id => "right-link"

.clear

app/views/users/_rating.html.haml
-if current_user.mates.include?(@user)
	.rated
		-@rating = Rating.find_by_user_id_and_mate_id(current_user.id, @user.id)
		-if @rating.status == "bang"
			You would totally hit that.
		-elsif @rating.status == "date"
			Aww you like them.
		-elsif @rating.status == "nope"
			Ugh, they are gross.
		-unless @user.mates.include?(current_user)
			-#= link_to "I changed my mind", user_rating_path(@user, @rating), :method => :delete, :remote => true
		-else
			-@message = Message.where("sender_id = ? AND receiver_id = ? OR sender_id = ? AND receiver_id = ?", current_user.id, @user.id, @user.id, current_user.id).first
			-unless @message.nil?
				%br/
				You like each other! 
				=link_to "Message #{@user.pronoun}", @message, :class => "white-button"
			-#-else
				-#= link_to "I changed my mind", user_rating_path(@user, @rating), :method => :delete, :remote => true
		
-else
	%p= link_to "I would bang #{@user.pronoun}", user_ratings_path(@user, :status => "bang"), :method => :post, :remote => true, :class => "white-button disable"
	%p= link_to "I would date #{@user.pronoun}", user_ratings_path(@user, :status => "date"), :method => :post, :remote => true, :class => "white-button disable"
	%p= link_to "Eww gross, no way.", user_ratings_path(@user, :status => "nope"), :method => :post, :remote => true, :class => "white-button disable"

app/views/users/_users.html.haml
%li
	= link_to user_path(user.login) do
		= image_tag user.profile_photo
		.fl.flfr{ :style => "margin-left: 10px;"}
			%h3= user.login
			= "#{user.age} year old #{user.looking_for.downcase} #{user.sex.downcase}"
			%br/
			= "#{user.city}," 
			= user.state
			%em.distance
				-unless user.distance_to(current_user.to_coordinates).nil?
					="(#{pluralize((user.distance_to(current_user.to_coordinates)).round, "mile")} away)"
			%br/
			- if user.sign_in_count > 0
				= "Last Online: #{time_ago_in_words(user.last_sign_in_at)} ago"
				%br/
			- if current_user.mates.include?(user)
				%em
					- @rating = Rating.find_by_user_id_and_mate_id(current_user.id, user.id)
					- if @rating.status == "bang"
						You would totally hit that.
					- elsif @rating.status == "date"
						Aww you like them.
					- elsif @rating.status == "nope"
						Ugh, they are gross. No way.
		.clear
.clear

/ %span{ :id => "hide_#{user.id}"}		
/	 = render :partial => 'users/hide', :locals => { :user => user }

app/views/users/index.html.haml
-title "Home"

-unless user_signed_in?
	.fl
		%h2.subtitle Not just personal ads.
		%h3#description Create a Profile. Upload Photos. Browse Profiles. |
										If you like the look of someone click ‘I would bang them’. | 
										If they click the same thing on your profile, you can message them.  Easy peasy. |

		%p#learn-more= link_to "Learn More", about_path, :class => "black-button fr", :style => "text-decoration: none;"

	.infinity-box-right{ :style => "margin-top: -87px;" }
		=form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
			%h3 Sign In
			%p
				= f.label :login, "Email Address or Username"
				%br/
				= f.text_field :login

			%p
				= f.label :password 
				%br/
				= f.password_field :password

			-if devise_mapping.rememberable?
				%p
					= f.check_box :remember_me
					= f.label :remember_me

			%p
				= f.submit "sign in", :class => "white-button"
				- if devise_mapping.recoverable? && controller_name != 'passwords'
					= link_to "Forgot your password?", new_password_path(resource_name), :style => "font-size: 12px;float:right;margin-top:10px;", :id => "forgot-password"
					%br/

	.clear

	.infinity-box-left.splash{ :style => "margin-top: -50px;" }
		= render :partial => 'users/registrations/sign_up'


-else

	-if current_user.photos.count == 0 || current_user.questions.map(&:answer).compact.empty? || current_user.ratings.count == 0
		= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
		%h2.fl{ :style => "font-size:72px; margin: 20px 0 0 25px;", :class => "logged-in-header"}
			Let’s find you someone 
			%br/ 
			to bang, shall we?
		.clear

	-if current_user.photos.count == 0
		.promo
			= link_to user_path(current_user.login) do
				%h3 Upload some pics
				.icon{ :style => "font-size:170px;"} p
				%p 
					No one is going to want to bang you if you don't have any photos.

	-if current_user.questions.map(&:answer).compact.empty?
		.promo
			= link_to user_about_path(current_user.login) do
				%h3 Answer Some Questions
				.icon{ :style => "font-size:170px;"} u
				%p
					Come on. You might be hot, but people like a good personality too.  

	-if current_user.ratings.count == 0
		.promo
			= link_to random_path do
				%h3= "Check out some #{current_user.looking_for_colloquial}"
				.icon{ :style => "font-size:170px;"} ✔
				%p
					Rate some hotties. Or notties.  
	.clear
	
	.user_list{ :style => "margin-right: 40px;" }
		%h3{ :style => "font-size:48px; margin: 25px 0;", :class => "subheader" }= "Here's some random #{current_user.looking_for_colloquial}."
		%ul.users
			= render :partial => 'users', :collection => @random, :as => :user

	.user_list
		%h3{ :style => "font-size:48px; margin: 25px 0;", :class => "subheader"}= "These #{current_user.looking_for_colloquial} are your best shot."
		%ul.users
			= render :partial => 'users', :collection => @similar, :as => :user

app/views/users/random.html.haml
-unless @user.nil?
	-title "Random - #{@user.login}"
	
	.profile-infinity-box-left.fixed
		= image_tag @user.profile_photo
		.fl{ :style => "margin-left: 10px;", :class => "flfr"}
			%h2= @user.login
			= "#{@user.age} year old #{@user.looking_for.downcase} #{@user.sex.downcase}"
			%br/
			= "#{@user.city}," 
			= @user.state
			%br/
			%em
				- unless @user.distance_to(current_user.to_coordinates).nil?
					="(#{pluralize((@user.distance_to(current_user.to_coordinates)).round, "mile")} away)"
			%br/
			- if @user.sign_in_count > 0
				= "Last Online: #{time_ago_in_words(@user.last_sign_in_at)} ago"
		.clear
		
		#rating
			-if current_user.mates.include?(@user)
				.rated
					-@rating = Rating.find_by_user_id_and_mate_id(current_user.id, @user.id)
					-if @rating.status == "bang"
						You would totally hit that.
					-elsif @rating.status == "date"
						Aww you like them.
					-elsif @rating.status == "nope"
						Ugh, they are gross.
					-unless @user.mates.include?(current_user)
						=link_to "Next Rando", random_path, :class => "white-button"
						-#= link_to "I changed my mind", user_rating_path(@user, @rating), :method => :delete
					-else
						-@message = Message.where("sender_id = ? AND receiver_id = ? OR sender_id = ? AND receiver_id = ?", current_user.id, @user.id, @user.id, current_user.id).first
						-unless @message.nil?
							%br/
							You like each other! 
							=link_to "Message #{@user.pronoun}", @message, :class => "white-button"
							=link_to "Next Rando", random_path, :class => "white-button"
						-else
							=link_to "Next Rando", random_path, :class => "white-button"
							-#= link_to "I changed my mind", user_rating_path(@user, @rating), :method => :delete
			-else
				%p= link_to "I would bang #{@user.pronoun}", user_rate_path(@user, :status => "bang"), :method => :post, :class => "white-button disable-random"
				%p= link_to "I would date #{@user.pronoun}", user_rate_path(@user, :status => "date"), :method => :post, :class => "white-button disable-random"
				%p= link_to "Eww gross, no way.", user_rate_path(@user, :status => "nope"), :method => :post, :class => "white-button disable-random"
				%p= link_to "Skip", random_path, :class => "white-button disable-random"
	
	.fr
		%nav#user
			%ul
				%li= link_to "photos", user_path(@user.login), :class => "current", :id => "left-link"
				%li= link_to "about", user_about_path(@user.login), :id => "right-link"
	
		.clear
		%ul#photos
			- if @user.photos.count > 0
				= render :partial => 'photos/photos', :collection => @user.photos.order('position ASC'), :as => :photo
			- else
				= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
				%h2.fl.profile-subheader{ :style => "font-size:36px; margin: 50px 0 0 25px;"} 
					= "#{@user.singular_pronoun} hasn't uploaded any"
					%br/ 
					photos yet.
					%br/
					Must be ugly.
		#about{ :style => "display:none;" }
			- unless @user.questions.map(&:answer).compact.nil? || @user.questions.map(&:answer).compact.blank?
				- @user.questions.order('created_at ASC').each do |question|
					.question
						- unless question.answer.nil?
							%h3
								= question.question
							%div{ :id => "#{question.id}_answer"}
								= simple_format(question.answer)
			- else
				= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
				%h2.fl.profile-subheader{ :style => "font-size:36px; margin: 50px 0 0 25px;"} 
					= "#{@user.singular_pronoun} hasn't answered any"
					%br/ 
					questions yet.
					%br/
					Must be dumb.
					
-else
	
	-title "No one to rate!"

	=image_tag "victorian-splash.gif", :class => "fl"
	
	.fl{ :style => "width: 600px;"}
		%h2 You've rated all the #{current_user.looking_for_colloquial}!
		%h3.no-messages= "Sorry, we're plum out of #{current_user.looking_for_colloquial} you'd like.  Better get some more #{current_user.looking_for_colloquial} on here!"

app/views/users/show.html.haml
- title "#{@user.login}"

- if @user == current_user
	- content_for(:head) do
		= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"
		:javascript
			$(document).ready(function(){
				$('#edit_photos').sortable({
					axis: 'y',
					dropOnEmpty: false,
					handle: '.handle',
					cursor: 'crosshair',
					items: 'li',
					opacity: 0.4,
					scroll: true,
					update: function(){
						$.ajax({
							type: 'post',
							data: $('#edit_photos').sortable('serialize'),
							dataType: 'script',
							url: "#{user_sort_path(@user)}"})
						}
					});
			});
			
	.profile-infinity-box-left
		= image_tag @user.profile_photo
		.fl.flfr{ :style => "margin-left: 10px;"}
			%h2= @user.login
			= "#{@user.age} year old #{@user.looking_for.downcase} #{@user.sex.downcase}"
			%br/
			= "#{@user.city}," 
			= @user.state
			%br/
			= link_to "edit your account", edit_user_registration_path
		.clear
		
		.upload-photo
		
			%h3 Upload a Photo
			- form_for([@user, @photo], :html => { :multipart => true }) do |f|
				%p
					=f.label :photo, "choose a photo from your hard drive"
					%br/
					= f.file_field :photo
				%p
					= f.label :caption, "write a caption for this photo"
					%br/
					= f.text_field :caption
				
				%p= f.submit "Upload Image", :class => "white-button"
			
				- if @user.photos.count > 0
					%h3{ :style => "margin-bottom:0;" } Edit Photos
					%h4{ :style => "margin:0;" } Drag to Reorder
					%ul#edit_photos
						- @user.photos.order('position ASC').each do |photo|
							%li{ :id => "photo_#{photo.id}"}
								= image_tag photo.photo.url(:medium)
								.links
									- unless photo.profile == true
										= link_to "make main photo", user_photo_make_profile_path(@user, photo)
										%br/
									- else
										Your Profile Photo
										%br/
									= link_to "re-crop thumbnail", [@user, photo]
									%br/
									= link_to "delete", [@user, photo], :method => :delete, :confirm => "Are you sure you want to delete this photo?"
								%span.handle [drag]
								.clear
	
	.fr
		= render :partial => 'nav'
		- if params[:action] == "about"
			%ul#photos{ :style => "display:none;" }
				= render :partial => 'photos/photos', :collection => @user.photos.order('position ASC'), :as => :photo
			#about
				- @user.questions.order('created_at ASC').each do |question|
					.question
						%h3
							= question.question
							%span.icon
								= link_to "✎", edit_user_question_path(current_user, question) , :class => "edit_button", :remote => true
						%div{ :id => "#{question.id}_answer"}
							= render :partial => 'questions/answer', :locals => { :question => question }
		- else
			%ul#photos
				- if @user.photos.count > 0
					= render :partial => 'photos/photos', :collection => @user.photos.order('position ASC'), :as => :photo
				- else
					= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
					%h2.fl.profile-subheader{ :style => "font-size:36px; margin: 50px 0 0 25px;"} 
						You haven't uploaded any
						%br/
						photos.Do it with the 
						%br/
						form on the left.
					.clear
			#about{ :style => "display:none;" }
				- @user.questions.order('created_at ASC').each do |question|
					.question
						%h3
							= question.question
							%span.icon
								= link_to "✎", edit_user_question_path(current_user, question) , :class => "edit_button", :remote => true
						%div{ :id => "#{question.id}_answer"}
							= render :partial => 'questions/answer', :locals => { :question => question }

	
- else

	.profile-infinity-box-left.fixed
		= image_tag @user.profile_photo
		.fl{ :style => "margin-left: 10px;", :class => "flfr"}
			%h2= @user.login
			= "#{@user.age} year old #{@user.looking_for.downcase} #{@user.sex.downcase}"
			%br/
			= "#{@user.city}," 
			= @user.state
			%br/
			%em
				- unless @user.distance_to(current_user.to_coordinates).nil?
					="(#{pluralize((@user.distance_to(current_user.to_coordinates)).round, "mile")} away)"
			%br/
			- if @user.sign_in_count > 0
				= "Last Online: #{time_ago_in_words(@user.last_sign_in_at)} ago"
		.clear
		#rating= render :partial => 'rating'
		.clear	
	
	.fr
		= render :partial => 'nav'
		- if params[:action] == "about"
			%ul#photos{ :style => "display:none;" }
				- if @user.photos.count > 0
					= render :partial => 'photos/photos', :collection => @user.photos.order('position ASC'), :as => :photo
				- else
					= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
					%h2.fl.profile-subheader{ :style => "font-size:236px; margin: 50px 0 0 25px;"} 
						= "#{@user.singular_pronoun} hasn't uploaded any"
						%br/ 
						photos yet. Must be ugly.
			#about
				- if @user.questions.map(&:answer).compact.nil? || @user.questions.map(&:answer).compact.blank?
					- @user.questions.order('created_at ASC').each do |question|
						.question
							- unless question.answer.nil?
								%h3
									= question.question
								%div{ :id => "#{question.id}_answer"}
									= simple_format(question.answer)
				- else
					= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
					%h2.fl.profile-subheader{ :style => "font-size:36px; margin: 50px 0 0 25px;"} 
						= "#{@user.singular_pronoun} hasn't answered any"
						%br/ 
						questions yet.
						%br/
						Must be dumb.
		- else
			%ul#photos
				- if @user.photos.count > 0
					= render :partial => 'photos/photos', :collection => @user.photos.order('position ASC'), :as => :photo
				- else
					= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
					%h2.fl.profile-subheader{ :style => "font-size:36px; margin: 50px 0 0 25px;"} 
						= "#{@user.singular_pronoun} hasn't uploaded any"
						%br/ 
						photos yet. 
						%br/
						Must be ugly.
			#about{ :style => "display:none;" }
				- unless @user.questions.map(&:answer).compact.nil? || @user.questions.map(&:answer).compact.blank?
					- @user.questions.order('created_at ASC').each do |question|
						- unless question.answer.nil?
							.question
								%h3
									= question.question
								%div{ :id => "#{question.id}_answer"}
									= simple_format(question.answer)
				- else
					= image_tag "victorian-home.gif", :class => "fl logged-in-victorian"
					%h2.fl.profile-subheader{ :style => "font-size:36px; margin: 50px 0 0 25px;"} 
						= "#{@user.singular_pronoun} hasn't answered any"
						%br/ 
						questions yet.
						%br/
						Must be dumb.