config/routes.rb
Bang::Application.routes.draw do

  match "/users/check_login" => "users#check_login"
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }
  root :to => "users#index"
  resources :photos, :only => ["index", "create"]
  resources :users, :only => ["show", "index"] do
    resources :photos do
      match "/users/:login" => 'users#show', :as => :login
      match "make_profile", :to => 'photos#make_profile'
      match "edit_caption", :to => 'photos#edit_caption'
      match "update_caption", :to => 'photos#update_caption'
      post :sort, on = :collection
    end
    resources :ratings  
    resources :questions, :only => ["edit", "update"]
    match "hide", :to => 'hides#create'
    match "unhide", :to => 'hides#destroy'
    match "sort", :to => 'photos#sort'
    match "rate", :to => 'ratings#browse_rate'
    match "answer_questions", :to => 'users#answer_questions'
    match "questions", :to => 'users#questions'
    match "about", :to => 'users#about'
  end
  match '/search', :to =>'users#search'
  match '/random', :to => 'users#random'
  match '/history', :to => 'users#history'
  match '/admin', :to => 'users#admin'
  match '/about', :to => 'users#learn_more'
  match '/contact', :to => 'users#contact'
  match '/send_contact', :to => 'users#send_contact'
  resources :messages do
    resources :responses
  end
  resources :questions, :only => [ :edit, :update ]
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_attached_file :photo, :styles => { 
                            :tiny => {:geometry => "30x30#", :processors => [:cropper]},
                            :thumb => {:geometry => "90x90#", :processors => [:cropper]}, 
                            :medium => {:geometry => "50x50#", :processors => [:cropper]},
                            :large => {
                              :geometry => "600x600>", 
                              :processors => [:watermark],
                              :watermark_path => "#{RAILS_ROOT}/public/images/watermark.png",
                              :position => 'SouthWest'
                              }
                            },
                            :storage => :s3, 
                            :s3_credentials => "#{RAILS_ROOT}/config/s3.yml", 
                            :path => ':id/:style'

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_photo, :if => :cropping?  
  
  def cropping?  
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?  
  end
  
  def photo_geometry(style = :original)  
    @geometry ||= {}  
    @geometry[style] ||= Paperclip::Geometry.from_file(photo.to_file(style))  
  end
  
  private  
  
  def reprocess_photo
    photo.reprocess!
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @user = User.find params[:user_id]
    @photo = Photo.new
  end
  
  def create
    @user = User.find params[:user_id]
    @photo = @user.photos.create(params[:photo])
    if @photo.save
      redirect_to user_photo_path(@user, @photo), :notice => "Successfully Uploaded.  Now Crop the Thumbnail."
    end
  end
  
  def show
    @photo = Photo.find params[:id]
    unless current_user.photos.include?(@photo)
      redirect_to root_path, :notice => "Hey! Get out of there! You're not allowed!"
    end
    @user = User.find params[:user_id]
  end
  
  def update
    @photo = Photo.find params[:id]
    @user = @photo.user
    @photo.update_attributes(params[:photo])
    if @photo.save
      redirect_to user_path(@user.login), :notice => "Photo Cropped!"
    end
  end
  
  def destroy
    @photo = Photo.find params[:id]
    @user = @photo.user
    @photo.destroy
    redirect_to user_path(@user.login), :notice => "Photo Deleted!"
  end
  
  def edit_caption
    @user = User.find params[:user_id]
    @photo = Photo.find params[:photo_id]
    respond_to do |format|
      format.js
    end
  end
  
  def update_caption
    @user = User.find params[:user_id]
    @photo = Photo.find params[:photo_id]
    if params[:caption]
      @photo.update_attributes(:caption => params[:caption])
    end
    respond_to do |format|
      format.js
    end
  end
  
  def make_profile
    @photo = Photo.find params[:photo_id]
    @user = User.find params[:user_id]
    @user.photos.where("profile = ?", true).each do |photo|
      photo.update_attributes(:profile => nil)
    end
    @photo.update_attributes(:profile => true)
    if @photo.save
      redirect_to user_path(@user.login), :notice => "New Profile Photo!"
    end
  end
  
  def sort
    @user = User.find params[:user_id]
    @user.photos.each do |photo|
      photo.position = params['photo'].index(photo.id.to_s) + 1
      photo.save
    end
    respond_to do |format|
      format.js { }
      format.html { redirect_to @video }
    end
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_caption.html.haml
%p{ :id => "#{photo.id}_photo_caption" }
	= photo.caption
	- if photo.user == current_user
		%span.icon
			= link_to "✎", user_photo_edit_caption_path(current_user, photo) , :class => "edit_button", :remote => true

app/views/photos/_edit_caption.html.haml
= form_tag user_photo_update_caption_path(current_user, @photo), :id => "edit_caption", :remote => true do
	
	= text_field_tag :caption, "#{@photo.caption}"
	= submit_tag "update caption", :class => "black-button"
	= link_to "cancel", user_photo_update_caption_path(current_user, @photo), :remote => true, :class => "cancel"

app/views/photos/_photos.html.haml
%li
	= image_tag photo.photo.url(:large)
	= render :partial => 'photos/caption', :locals => { :photo => photo }

app/views/photos/edit_caption.js.erb
$("p#<%= @photo.id %>_photo_caption").html("<%= escape_javascript(render :partial => 'edit_caption', :photo => @photo) %>");
$("#edit_caption").validate({
	rules: {
		caption: {
			maxlength: 255
		}
	},
	messages: {
		caption: {
			maxLength: "Captions are maximum 255 characters."
		}
	},
});

app/views/photos/index.html.erb
<% title "#{@user.login}'s Photos" %>

app/views/photos/show.html.erb
<% title "Crop this Photo" %>
<% content_for(:head) do %>
	<%= stylesheet_link_tag "jquery.Jcrop" %>
	<%= javascript_include_tag "jquery.Jcrop.min" %>
	<script type="text/javascript" charset="utf-8">
		$(function() {
	  	$('#cropbox').Jcrop({
				onChange: update_crop,  
				onSelect: update_crop,  
				setSelect: [0, 0, 90, 90],  
				aspectRatio: 1
			});
			function update_crop(coords) {
				var rx = 100/coords.w;  
				  var ry = 100/coords.h;  
				  $('#preview').css({  
				    width: Math.round(rx * <%= @photo.photo_geometry(:large).width %>) + 'px',  
				    height: Math.round(ry * <%= @photo.photo_geometry(:large).height %>) + 'px',  
				    marginLeft: '-' + Math.round(rx * coords.x) + 'px',  
				    marginTop: '-' + Math.round(ry * coords.y) + 'px'  
				  });
				
			  var ratio = <%= @photo.photo_geometry(:original).width %> / <%= @photo.photo_geometry(:large).width %>;   
				  $('#crop_x').val(Math.floor(coords.x * ratio));  
				  $('#crop_y').val(Math.floor(coords.y * ratio));  
				  $('#crop_w').val(Math.floor(coords.w * ratio));  
				  $('#crop_h').val(Math.floor(coords.h * ratio));  
			}
		});
	</script>
<% end %>

<div class="fl">
	<h2>Crop This Photo</h2>
	<%= image_tag @photo.photo.url(:large), :id => "cropbox" %>
</div>

<div class="fl" style="margin: 50px 0 0 25px">
	<h4 style="margin-bottom: 0;">Preview</h4>  
	<div style="width: 90px; height: 90px; overflow: hidden;">  
  	<%= image_tag @photo.photo.url(:large), :id => "preview" %>  
	</div>
	<% form_for [@user, @photo] do |f| %>
		<% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>  
			<%= f.hidden_field attribute, :id => attribute %>  
		<% end %>
		<%= f.submit "Crop Photo", :class => "black-button", :style => "margin-top: 25px" %>
	<% end %>
</div>

<div class="clear"></div>

app/views/photos/sort.js.erb
$("#photos").html("<%= escape_javascript(render :partial => 'photos', :collection => @user.photos.order('position ASC'), :as => :photo) %>");

app/views/photos/update_caption.js.erb
$("p#<%= @photo.id %>_photo_caption").html("<%= escape_javascript(render :partial => 'caption', :locals => { :photo => @photo }) %>");