config/routes.rb
Bang::Application.routes.draw do

  match "/users/check_login" => "users#check_login"
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords" }
  root :to => "users#index"
  resources :photos, :only => ["index", "create"]
  resources :users, :only => ["show", "index"] do
    resources :photos do
      match "/users/:login" => 'users#show', :as => :login
      match "make_profile", :to => 'photos#make_profile'
      match "edit_caption", :to => 'photos#edit_caption'
      match "update_caption", :to => 'photos#update_caption'
      post :sort, on = :collection
    end
    resources :ratings  
    resources :questions, :only => ["edit", "update"]
    match "hide", :to => 'hides#create'
    match "unhide", :to => 'hides#destroy'
    match "sort", :to => 'photos#sort'
    match "rate", :to => 'ratings#browse_rate'
    match "answer_questions", :to => 'users#answer_questions'
    match "questions", :to => 'users#questions'
    match "about", :to => 'users#about'
  end
  match '/search', :to =>'users#search'
  match '/random', :to => 'users#random'
  match '/history', :to => 'users#history'
  match '/admin', :to => 'users#admin'
  match '/about', :to => 'users#learn_more'
  match '/contact', :to => 'users#contact'
  match '/send_contact', :to => 'users#send_contact'
  resources :messages do
    resources :responses
  end
  resources :questions, :only => [ :edit, :update ]
  
end

app/views/layouts/_messages.html.haml
= link_to messages_path do
	messages
	-unless unread_messages < 1
		= "(#{unread_messages})"

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title= "#{content_for?(:title) ? yield(:title) : ""} - I Would Bang You"
		%link{ :rel => "icon",  :href => "/favicon.png", :type => "image/png"}
		= stylesheet_link_tag 'css'
		<link rel="stylesheet" type="text/css" media="only screen and (max-width: 480px), only screen and (max-device-width: 480px)" href="/stylesheets/mobile.css" />
		<link rel="stylesheet" type="text/css" media="only screen and (min-device-width: 481px) and (max-width: 1024px)" href="/stylesheets/tablet.css" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js'
		= javascript_include_tag 'protoFluid3.02.js'
		= javascript_include_tag 'rails'
		= javascript_include_tag 'jquery.validate.min.js'
		= javascript_include_tag 'application'
		= csrf_meta_tag
		/[if lt IE 9]
			%script{ :src => "http://html5shim.googlecode.com/svn/trunk/html5.js" }
		= yield(:head)
		:javascript
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-27731822-1']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
	
	%body
  	
		%header.main
			#content
				%h1= link_to "I Would Bang You", root_path
				%nav
					-if user_signed_in?
						%ul
							%li= link_to "home", root_path
							%li#messages= render :partial => "layouts/messages"
							%li= link_to "random", random_path
							%li= link_to "search", search_path
							%li#profile
								= link_to user_path(current_user.login) do
									= image_tag current_user.nav_photo
									= current_user.login
									%span.icon{ :style => "font-size: 10px;"} ↓
								.clear
								%ul#subnav
									-if current_user == User.find_by_login("goddamnyouryan")
										%li= link_to "admin", admin_path
									%li= link_to "view / edit my profile", user_path(current_user.login)
									%li= link_to "history", history_path
									%li= link_to "account settings", edit_user_registration_path
									%li#logout= link_to "logout", destroy_user_session_path, :method => :delete
					-else
						%ul
							%li= link_to "register", new_user_registration_path
							%li= link_to "sign in", new_user_session_path
		.clear
		
		-flash.each do |name, msg|
			= content_tag :div, raw(msg), :id => "flash_#{name}", :class => "flash"
		
		#container.logged_in
			= yield
		.clear
		
		%footer
			#container
				.fl
					%h1= link_to "I Would Bang You", root_path
					%p!= "&copy; #{Time.now.year} #{link_to "Ryan MacInnes", user_path("goddamnyouryan")}"
				.fl{ :style => "margin: 0 0 50px 100px", :class => "footer-links"}
					%nav.logged_in
						.fl
							%ul
								%li= link_to "Home", root_path
								%li= link_to "My Profile", user_path(current_user.login)
								%li{ :style => "text-transform: capitalize;"}= render :partial => "layouts/messages"
								%li= link_to "Search", search_path
								
						.fl{ :style => "margin-left: 264px;", :class => "footer-column" }
							%ul
								%li= link_to "Edit My Profile", user_path(current_user.login)
								%li= link_to "History", history_path
								%li= link_to "Account Settings", edit_user_registration_path
								%li= link_to "Logout", destroy_user_session_path, :method => :delete
								
						.fl{ :style => "margin-left: 263px;", :class => "footer-column" }
							%ul
								%li
									= link_to image_tag('twitter.png'), "http://www.twitter.com/iwouldbangyou", :target => "_blank"
									= link_to image_tag('facebook.png'), "http://www.facebook.com/pages/Iwouldbangyou/215857168475583", :target => "_blank"
								%li= link_to "About", about_path
								%li= link_to "Contact", contact_path
				.clear
					= link_to "Go to a random #{current_user.looking_for_colloquial} profile", random_path, :class => "white-button bottom-random"

app/views/layouts/email.html.haml
!!! 5
%html
	%head
	%body{ :style => 'background: #f3f2f0;color: #000!important;font-family: Helvetica, Arial, Sans-Serif; padding: 10px 25px;' }
	
		%h1
			=link_to "I Would Bang You", "http://www.iwouldbangyou.com/", :style => 'color: #000; text-decoration:none; font-size: 48px;'
		=yield
		%p{ :style => 'border-top: 1px solid #999; padding: 25px 0 10px; margin-top:50px; color: #999;'}
			Don't want to receive emails from I Would Bang You?
			=link_to 'Click here', edit_user_registration_url, :style => 'color:#000;'
			to unsubscribe.

app/views/layouts/splash.html.haml
!!! 5
%html
	%head
		%title I Would Bang You - The Best Thing to Ever Happen to Online Dating
		%link{ :rel => "icon",  :href => "/favicon.png", :type => "image/png"}
		= stylesheet_link_tag 'css'
		<link rel="stylesheet" type="text/css" media="only screen and (max-width: 480px), only screen and (max-device-width: 480px)" href="/stylesheets/mobile.css" />
		<link rel="stylesheet" type="text/css" media="only screen and (min-device-width: 481px) and (max-width: 1024px)" href="/stylesheets/tablet.css" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js'
		= javascript_include_tag 'rails'
		= javascript_include_tag 'jquery.validate.min.js'
		= javascript_include_tag 'splash'
		= javascript_include_tag 'date'
		= csrf_meta_tag
		/[if lt IE 9]
			%script{ :src => "http://html5shim.googlecode.com/svn/trunk/html5.js" }
		= yield(:head)
		:javascript
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-21462046-2']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

	%body
	
		#splash-container
			%header
				%h1= link_to "I Would Bang You", root_path
			-flash.each do |name, msg|
				= content_tag :div, raw(msg), :id => "flash_#{name}_splash", :class => "flash"
			= yield
		.clear
			
		%footer
			#container
				.fl
					%h1= link_to "I Would Bang You", root_path
					%p!= "&copy; #{Time.now.year} #{link_to "Ryan MacInnes", "http://www.goddamnyouryan.com/"}"
					%p
						= link_to image_tag('twitter.png'), "http://www.twitter.com/iwouldbangyou", :target => "_blank"
						= link_to image_tag('facebook.png'), "http://www.facebook.com/pages/Iwouldbangyou/215857168475583", :target => "_blank"
					%p
						<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FIwouldbangyou%2F215857168475583&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=35&amp;appId=267556526607973" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe>
				.fr
					%nav
						%ul
							%li= link_to "Home", root_path
							%li= link_to "Sign Up", new_user_registration_path
							%li= link_to "Login", new_user_session_path
							%li= link_to "About", about_path
							%li= link_to "Contact", contact_path
				.clear
			